<?php

namespace FarmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Cart_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cart_productRepository extends EntityRepository
{
}
